name: test tools
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'test'
        type: string
        required: true
  pull_request:

run-name: Continuous integration for ${{ github.ref_name }} by @${{ github.actor }}

concurrency:
  group: "ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  value_changed:
   uses: ./.github/workflows/test.value.yaml
   with:
    version: ${{ inputs.version }}

  pattern_branch_lints:
    uses: ./.github/workflows/module.branch.lint.yaml

  commitlint:
    uses: ./.github/workflows/module.commitlint.yaml
