name: test tools
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'test'
        type: string
        required: true
  pull_request:

jobs:
  test_pr:
    runs-on: ubuntu-22.04

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: first test
        run: echo "hello word"

  value_changed:
    if: ${{ github.event.inputs.version }} == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    needs: test_pr

    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Update pubspec.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'version'
          value: ${{ inputs.version }}
          commitChange: false
      - run: cat pubspec.yaml

  commitlint:
    uses: ./.github/workflows/module.commitlint.yaml
