name: Conventional Commits

on:
  workflow_call:
    inputs:
      runnerLabel:
        required: false
        type: string
        default: ubuntu-22.4
      node-version:
        required: false
        type: string
        default: lts/*

jobs:
  commitlint:
    name: Validate conventional commits
    runs-on: ${{ inputs.runnerLabel }}
    timeout-minutes: 20
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - uses: wagoid/commitlint-github-action@v4
